version: "3.8"

services:
    e2e:
        build: .
        environment:
            DATABASE_URL: ${DATABASE_URL}
            FRONTEND_URL: "kirjasto:8001"
            SELENIUM_REMOTE_URL: "http://localhost:4444/wd/hub"
            CUCUMBER_PUBLISH_ENABLED: "true"
        volumes:
            - ./src:/usr/src/app/src
            - ./features:/usr/src/app/features
        depends_on:
            - frontend
            - selenium
        network_mode: "host"
        
    selenium:
        image: selenium/standalone-chrome
        network_mode: "host"
        extra_hosts:
            - "kirjasto:127.0.0.1"
        shm_size: 2g

    frontend:
        build:
            context: ${FRONTEND_LOCATION}
            target: dev
        container_name: kirjasto-frontend-dev
        image: kirjasto-frontend-dev
        environment:
            PORT: 8001
            BACKEND_URL: "localhost:8000"
        volumes:
            - ${FRONTEND_LOCATION}/src:/usr/src/app/src
            - ${FRONTEND_LOCATION}/webpack.dev.js:/usr/src/app/webpack.dev.js
            - ${FRONTEND_LOCATION}/webpack.common.js:/usr/src/app/webpack.common.js

        depends_on:
            - backend
        network_mode: "host"
        restart: on-failure

    backend:
        build:
            context: ${BACKEND_LOCATION}
            target: dev
        container_name: kirjasto-backend-dev
        environment:
            DATABASE_URL: ${DATABASE_URL}
            PORT: 8000
        volumes:
            - ${BACKEND_LOCATION}:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db
        network_mode: "host"
        restart: on-failure
            
    db:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        network_mode: "host"
        command: ["postgres", "-c", "log_statement=all"]
        restart: on-failure
