version: "3.8"

x-pg-env:
    &pg-env
    PGHOST: ${PGHOST}
    PGDATABASE: ${PGDATABASE}
    PGUSER: ${PGUSER}
    PGPASSWORD: ${PGPASSWORD}
    # postgres image uses the POSTGRES_PASSWORD environment variable instead of PGPASSWORD
    POSTGRES_PASSWORD: ${PGPASSWORD}

services:

    frontend:
        build:
            context: ${FRONTEND_LOCATION}
            target: dev
        container_name: kirjasto-frontend-dev
        image: kirjasto-frontend-dev
        environment:
            PORT: 8001
            BACKEND_URL: "localhost:8000"
        volumes:
            - ${FRONTEND_LOCATION}:/usr/src/app/
        depends_on:
            - backend
        network_mode: "host"

    backend:
        build: ${BACKEND_LOCATION}
        environment:
            <<: *pg-env
            PORT: 8000
            AUTH0SECRET: ${AUTH0SECRET}
        volumes:
            - ${BACKEND_LOCATION}:/usr/src/app
        depends_on:
            - db
        network_mode: "host"
        command: ["npm", "run", "wait", "development"]
            
    db:
        image: postgres
        environment:
            <<: *pg-env
            POSTGRES_PASSWORD: ${PGPASSWORD}
        network_mode: "host"
        command: ["postgres", "-c", "log_statement=all"]
