version: "3.8"

x-pg-env:
    &pg-env
    PGHOST: ${PGHOST}
    PGDATABASE: ${PGDATABASE}
    PGUSER: ${PGUSER}
    PGPASSWORD: ${PGPASSWORD}
    # postgres image uses the POSTGRES_PASSWORD environment variable instead of PGPASSWORD
    POSTGRES_PASSWORD: ${PGPASSWORD}

services:
    e2e:
        build: .
        environment:
            <<: *pg-env
            FRONTEND_URL: "localhost:8001"
            SELENIUM_REMOTE_URL: "http://localhost:4444/wd/hub"
            CUCUMBER_PUBLISH_ENABLED: "true"
        depends_on:
            - frontend
            - selenium
        network_mode: "host"
        command: ["npm", "run", "wait", "test"]
        
    selenium:
        image: selenium/standalone-chrome
        network_mode: "host"
