version: "3.8"
services:
    e2e:
        build: .
        environment:
            - FRONTEND_URL=frontend:8001
            - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
            - PGHOST=db
            - PGDATABASE=postgres
            - PGUSER=postgres
            - PGPASSWORD=${POSTGRES_PASSWORD}
            - CUCUMBER_PUBLISH_ENABLED=true
        depends_on:
            - frontend
            - selenium
            - db
        command: test
        
    selenium:
        image: selenium/standalone-chrome
        ports:
            - "4444:4444"

    frontend:
        build: ${FRONTEND_LOCATION}
        ports:
            - "8001:8001"
        environment:
            - PORT=8001
            - BACKEND_URL=backend:8000
        depends_on:
            - backend
        command: run development

    backend:
        build: ${BACKEND_LOCATION}
        ports:
            - "8000:8000"
        environment:
            - PORT=8000
            - PGHOST=db
            - PGDATABASE=postgres
            - PGUSER=postgres
            - PGPASSWORD=${POSTGRES_PASSWORD}
        depends_on:
            - db
        command: run development
            
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        command: ["postgres", "-c", "log_statement=all"]
