name: Continuous Deployment

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [frontend_push, backend_push]
 
env:
  FRONTEND_LOCATION: ./kirjasto-frontend
  BACKEND_LOCATION: ./kirjasto-backend

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout kirjasto
        uses: actions/checkout@v2
        
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: vuolen/kirjasto-frontend
          path: kirjasto-frontend
          
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: vuolen/kirjasto-backend
          path: kirjasto-backend
      
      - name: Run E2E tests
        run: docker-compose -f e2e.yml run e2e
        env:
          BACKEND_URL: backend:8000
          POSTGRES_PASSWORD: e2etest
  
      - name: Deploy frontend
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kirjasto-demo"
          heroku_email: "vuolanne.lennu@gmail.com"
          appdir: "kirjasto-frontend"
