name: Continuous Deployment

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [frontend_push, backend_push]
 
env:
  FRONTEND_LOCATION: ./kirjasto-frontend
  BACKEND_LOCATION: ./kirjasto-backend

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout kirjasto
        uses: actions/checkout@v2
        
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: vuolen/kirjasto-frontend
          path: kirjasto-frontend
          
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: vuolen/kirjasto-backend
          path: kirjasto-backend
      
      - name: Run E2E tests
        run: ./dev-env.sh run e2e
        env:
          BACKEND_URL: localhost:8000
          POSTGRES_PASSWORD: e2etest
  
      - name: Login to Heroku
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          
      - name: Deploy frontend
        run: |
          docker build --target prod -t registry.heroku.com/kirjasto-demo/web kirjasto-frontend
          docker push registry.heroku.com/kirjasto-demo/web
          heroku container:release web
          
      - name: Deploy backend
        run: |
          docker build --target prod -t registry.heroku.com/kirjasto-backend/web kirjasto-backend
          docker push registry.heroku.com/kirjasto-backend/web
          heroku container:release web
