name: E2E tests

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [frontend_push, backend_push]
 
env:
  FRONTEND_LOCATION: ../kirjasto-frontend
  BACKEND_LOCATION: ../kirjasto-backend
  BACKEND_URL: backend:8000
  POSTGRES_PASSWORD: e2etest

jobs:

  e2e_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: vuolen/kirjasto-frontend
        path: $FRONTEND_LOCATION
    - uses: actions/checkout@v2
      with:
        repository: vuolen/kirjasto-backend
        path: $BACKEND_LOCATION
    - uses: actions/checkout@v2
    - run: docker-compose run e2e
